/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/**/*.{js,jsx,ts,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        arabic: ['Tajawal', 'sans-serif'],
      },
      colors: {
          border: "hsl(var(--border))",
          input: "hsl(var(--input))",
          ring: "hsl(var(--ring))",
          background: "hsl(var(--background))",
          foreground: "hsl(var(--foreground))",
          primary: {
            50: "hsl(var(--primary-50))",
            100: "hsl(var(--primary-100))",
            200: "hsl(var(--primary-200))",
            300: "hsl(var(--primary-300))",
            400: "hsl(var(--primary-400))",
            500: "hsl(var(--primary-500))",
            600: "hsl(var(--primary-600))",
            700: "hsl(var(--primary-700))",
            800: "hsl(var(--primary-800))",
            900: "hsl(var(--primary-900))",
            950: "hsl(var(--primary-950))",
            DEFAULT: "hsl(var(--primary))",
            foreground: "hsl(var(--primary-foreground))",
          },
          secondary: {
            50: "hsl(var(--secondary-50))",
            100: "hsl(var(--secondary-100))",
            200: "hsl(var(--secondary-200))",
            300: "hsl(var(--secondary-300))",
            400: "hsl(var(--secondary-400))",
            500: "hsl(var(--secondary-500))",
            600: "hsl(var(--secondary-600))",
            700: "hsl(var(--secondary-700))",
            800: "hsl(var(--secondary-800))",
            900: "hsl(var(--secondary-900))",
            950: "hsl(var(--secondary-950))",
            DEFAULT: "hsl(var(--secondary))",
            foreground: "hsl(var(--secondary-foreground))",
          },
          accent: {
            50: "hsl(var(--accent-50))",
            100: "hsl(var(--accent-100))",
            200: "hsl(var(--accent-200))",
            300: "hsl(var(--accent-300))",
            400: "hsl(var(--accent-400))",
            500: "hsl(var(--accent-500))",
            600: "hsl(var(--accent-600))",
            700: "hsl(var(--accent-700))",
            800: "hsl(var(--accent-800))",
            900: "hsl(var(--accent-900))",
            950: "hsl(var(--accent-950))",
            DEFAULT: "hsl(var(--accent))",
            foreground: "hsl(var(--accent-foreground))",
          },
          destructive: {
            DEFAULT: "hsl(var(--destructive))",
            foreground: "hsl(var(--destructive-foreground))",
          },
          muted: {
            DEFAULT: "hsl(var(--muted))",
            foreground: "hsl(var(--muted-foreground))",
          },
          popover: {
            DEFAULT: "hsl(var(--popover))",
            foreground: "hsl(var(--popover-foreground))",
          },
          card: {
            DEFAULT: "hsl(var(--card)/ 0.8)",
            foreground: "hsla(var(--card-foreground))",
          },
          neutral: {
            50: "hsl(var(--neutral-50))",
            100: "hsl(var(--neutral-100))",
            200: "hsl(var(--neutral-200))",
            300: "hsl(var(--neutral-300))",
            400: "hsl(var(--neutral-400))",
            500: "hsl(var(--neutral-500))",
            600: "hsl(var(--neutral-600))",
            700: "hsl(var(--neutral-700))",
            800: "hsl(var(--neutral-800))",
            900: "hsl(var(--neutral-900))",
            950: "hsl(var(--neutral-950))",
          },
          sidebar: {
            DEFAULT: "hsl(var(--sidebar-background))",
            foreground: "hsl(var(--sidebar-foreground))",
            primary: "hsl(var(--sidebar-primary))",
            "primary-foreground": "hsl(var(--sidebar-primary-foreground))",
            accent: "hsl(var(--sidebar-accent))",
            "accent-foreground": "hsl(var(--sidebar-accent-foreground))",
            border: "hsl(var(--sidebar-border))",
            ring: "hsl(var(--sidebar-ring))",
          },
        },
      },
    },
  plugins: [require('daisyui')],
}